### ISSUE TITLE
If no emptyroom is present - compensation grade is still checked 

### ISSUE THREAD

**Issue by jstout211** [jstout211/enigma_MEG#32]
ERROR:23490_ses_None:vendor_prep :: 'NoneType' object has no attribute 'compensation_grade'
Traceback (most recent call last):
  File "/vf/users/MEGmodules/modules/enigma_meg0.5_extras/enigma_MEG/enigmeg/process_meg.py", line 78, in wrapper
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vf/users/MEGmodules/modules/enigma_meg0.5_extras/enigma_MEG/enigmeg/process_meg.py", line 447, in vendor_prep
    if self.raw_eroom.compensation_grade != 3:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'compensation_grade'
Traceback (most recent call last):
  File "/vf/users/MEGmodules/modules/enigma_meg0.5/bin/process_meg.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/vf/users/MEGmodules/modules/enigma_meg0.5_extras/enigma_MEG/enigmeg/process_meg.py", line 1403, in <module>
    process_subject(args.subject, args)  # process the single specified subject
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vf/users/MEGmodules/modules/enigma_meg0.5_extras/enigma_MEG/enigmeg/process_meg.py", line 1134, in process_subject
    proc.do_proc_allsteps()
  File "/vf/users/MEGmodules/modules/enigma_meg0.5_extras/enigma_MEG/enigmeg/process_meg.py", line 836, in do_proc_allsteps
    self.vendor_prep()
  File "/vf/users/MEGmodules/modules/enigma_meg0.5_extras/enigma_MEG/enigmeg/process_meg.py", line 78, in wrapper
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vf/users/MEGmodules/modules/enigma_meg0.5_extras/enigma_MEG/enigmeg/process_meg.py", line 447, in vendor_prep
    if self.raw_eroom.compensation_grade != 3:

**Comment by jstout211** [comment]
Solved in previous commit
